pipeline:
  name: Pipeline1
  identifier: Pipeline1
  projectIdentifier: CITestDemoProBz7avWUCST
  orgIdentifier: CITestDemoOrguFybcCSw6g
  tags: {}
  stages:
    - stage:
        name: fd
        identifier: fd
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo $HOME
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    connectorRef: account.CItestDockerConnectorAA4qRASwHN
                    image: alpine
                    shell: Sh
                    command: echo $HOME
                  when:
                    stageStatus: All
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: echo $HOME
                  strategy:
                    parallelism: 5
