pipeline:
  name: fd
  identifier: fd
  projectIdentifier: HarshProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fd
        identifier: fd
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo a
